name: Nuxtjs with versioned node

on: [push]

jobs:
  nuxtjs-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm ci
    - name: Execute tests
      run: |
        npm run test
